name: Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm install and npm Build
        run: |
          npm i
          npm run build

      - name: copy file to server        
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            server: ${{ secrets.HOST }}
            username: satedu
            port: 22
            local_path: './dist/*'
            remote_path: '/home/tsri-hosting/satedu/www'
            sftp_only: true
            password: ${{ secrets.PASSWORD }}

      - name: copy access to server      
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            server: ${{ secrets.HOST }}
            username: satedu
            port: 22
            local_path: './.htaccess'
            remote_path: '/home/tsri-hosting/satedu/www'
            sftp_only: true
            password: ${{ secrets.PASSWORD }}